name: Update ZipZAP M3U
on:
  schedule:
    # Her gün öğlen 12:00 UTC'de çalışır
    - cron: '0 12 * * *'
  workflow_dispatch:
    # İsteğe bağlı: Depo sayfasından manuel olarak çalıştırmaya izin verir

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Depoyu Çek
        uses: actions/checkout@v4

      - name: 📦 M3U İçeriğini Worker URL'den Çekme
        id: fetch_m3u
        run: |
          # DİKKAT: Aşağıdaki URL'yi kendi Worker URL'niz ile değiştirin
          WORKER_URL="http://smart.aio-digital.workers.dev/TV.php?ID=https://zipzaptv.com/"
          
          # Worker'dan gelen içeriği bir dosyaya kaydet
          curl -sS "$WORKER_URL" > ZipZAP.m3u
          
      - name: ⚙️ Değişiklik Var mı Kontrol Et
        id: git_status
        run: echo "changes=$(git status --porcelain)" >> $GITHUB_OUTPUT

      - name: ⬆️ Değişiklikleri Kaydet (Commit) ve Gönder (Push)
        if: ${{ steps.git_status.outputs.changes != '' }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "action@github.com"
          git add ZipZAP.m3u
          git commit -m "Auto update: Fetch latest ZipZAP M3U from Worker"
          git push