name: YouTube Liste Guncelleyici

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4

      - name: Veriyi Cek
        run: |
          curl -L -k -s "https://live.weebtv.workers.dev/" -o YouTube.json

      - name: Dosya Kontrol
        run: |
          if [ ! -s YouTube.json ]; then
            echo "HATA: Veri cekilemedi veya dosya bos!"
            exit 1
          fi

      - name: Kaydet ve Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add YouTube.json
          git commit -m "YouTube.json Guncellendi: $(date)" || exit 0
          git push origin main
